"""add composite index conversations(user_id, updated_at)

Supports the hot conversation-list query:

    SELECT ... FROM conversations
     WHERE user_id = :uid
     ORDER BY updated_at DESC
     LIMIT :n OFFSET :m

The pre-existing single-column ix_conversations_user_id satisfies the WHERE but
leaves the ORDER BY as a sort over every conversation the user owns. This
composite serves the filter and the ordering from one index, so the paged list is
an index range scan.

Declared ASC: with the leading column pinned by equality the engine walks the
index backwards for ORDER BY updated_at DESC, so an explicit DESC index buys
nothing and would make this a non-portable expression index instead of a plain
(reflectable) column index on SQLite and Postgres alike.

Revision ID: 1132c99cc5af
Revises: 17d0d0b91fb9
Create Date: 2026-08-02 19:40:34.852464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1132c99cc5af'
down_revision: Union[str, Sequence[str], None] = '17d0d0b91fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_user_updated', ['user_id', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_user_updated')

    # ### end Alembic commands ###
