"""Prava wallet integration — signing, the signed client, and the shop broker.

No network. Every wallet call is driven against a stub, so nothing here can
reach pay-api.prava.space and no spend is possible.

The signing cases carry KNOWN-ANSWER VECTORS produced by the reference
implementation itself (`@prava-sdk/cli` v3.1.0, node:crypto). That is the point
of them: a Python signature that merely round-trips against Python proves
nothing about whether Prava's server will accept it. These bytes came out of
Node, and if a refactor changes ours, these fail.

Runs under pytest, and standalone (`uv run python tests/test_prava_wallet.py`),
matching the house style in this directory.
"""

from __future__ import annotations

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.brokers.prava_shop import (  # noqa: E402
    PravaShopBroker,
    PravaShopError,
    merchant_domain,
    search_query,
)
from app.contracts import (  # noqa: E402
    CheckoutState,
    CartItem,
    Merchant,
    PaymentCredential,
    PurchaseContext,
)
from app.prava.signing import (  # noqa: E402
    canonical_create_message,
    generate_keypair,
    js_encode_uri_component,
    public_key_b64,
    sign_create_params,
    sign_request,
    verify_request,
)
from app.prava.wallet import WalletClient, WalletError  # noqa: E402

# ── Known-answer vectors, generated by the Node reference implementation ─────
# Deterministic Ed25519 key from the fixed seed 0011..eeff, PKCS8-wrapped.
VEC_PRIVATE = "MC4CAQAwBQYDK2VwBCIEIAARIjNEVWZ3iJmqu8zd7v8AESIzRFVmd4iZqrvM3e7/"
VEC_PUBLIC = "MCowBQYDK2VwAyEAPM0kHP/Js2GARLl9A22GFFk9iwF8NA8d7odzOFUXZUs="
VEC_TIMESTAMP = "1785000000"
VEC_BODY = '{"query":"dark roast coffee","limit":5}'
VEC_REQUEST_SIG = (
    "JLJ1MopJ+9dsTULff6+YE8x+1GrK+nocuMVLaIknVeZXU9D5Mkzr+Cjo7EJsuKmeXfi7C576LED8jl8Vu90TBg=="
)
VEC_DESCRIPTION = "Errand — grocery/pantry agent (100% policy-bound)"
VEC_CANONICAL = (
    "d=Errand%20%E2%80%94%20grocery%2Fpantry%20agent%20(100%25%20policy-bound)"
    "&iat=1785000000&n=Errand%20Agent&p=custom"
    "&pk=MCowBQYDK2VwAyEAPM0kHP%2FJs2GARLl9A22GFFk9iwF8NA8d7odzOFUXZUs%3D"
)
VEC_CREATE_SIG = "I_tzKLR-EZRiXzWRFv9uikkSxeBNx_vlNqsB9xTG9ydvd0sIqPAZNhYK2GbVp-cIIhEBXPSHKsTh-DWM-JY_Dg"


# ── signing ───────────────────────────────────────────────────────────────────

def test_request_signature_matches_the_node_reference() -> None:
    """A byte-for-byte match with node:crypto's `signRequest`.

    Ed25519 is deterministic, so the same key over the same message yields the
    same signature in any correct implementation. A mismatch here means the
    wallet would answer AUTH_INVALID_SIGNATURE and say nothing further.
    """
    assert sign_request(VEC_PRIVATE, VEC_TIMESTAMP, VEC_BODY) == VEC_REQUEST_SIG


def test_public_key_derivation_matches_the_node_reference() -> None:
    assert public_key_b64(VEC_PRIVATE) == VEC_PUBLIC


def test_link_canonical_and_signature_match_the_node_reference() -> None:
    """The canonical string is the fragile half — one byte off and it's rejected."""
    canonical = canonical_create_message(
        public_key=VEC_PUBLIC,
        name="Errand Agent",
        platform="custom",
        description=VEC_DESCRIPTION,
        iat=1785000000,
    )
    assert canonical == VEC_CANONICAL
    assert (
        sign_create_params(
            VEC_PRIVATE,
            public_key=VEC_PUBLIC,
            name="Errand Agent",
            platform="custom",
            description=VEC_DESCRIPTION,
            iat=1785000000,
        )
        == VEC_CREATE_SIG
    )


def test_percent_encoding_follows_javascript_not_python() -> None:
    """`quote()`'s default safe set is not `encodeURIComponent`'s.

    Two differences bite: Python leaves `/` unescaped by default (JS escapes it,
    and base64 public keys are full of it), and JS leaves `!*'()~` alone.
    """
    assert js_encode_uri_component("a b/c~d!e*f'g(h)i%j+k") == "a%20b%2Fc~d!e*f'g(h)i%25j%2Bk"


def test_signature_verifies_and_is_bound_to_the_body() -> None:
    keys = generate_keypair()
    signature = sign_request(keys.private_key, "1700000000", '{"a":1}')
    assert verify_request(keys.public_key, "1700000000", '{"a":1}', signature)
    # A different body or timestamp must not verify — that binding is the whole
    # protection against a replayed or tampered request.
    assert not verify_request(keys.public_key, "1700000000", '{"a":2}', signature)
    assert not verify_request(keys.public_key, "1700000001", '{"a":1}', signature)


# ── the signed client ─────────────────────────────────────────────────────────

class _StubResponse:
    def __init__(self, status_code: int, payload: object) -> None:
        self.status_code = status_code
        self._payload = payload

    def json(self) -> object:
        return self._payload


class _StubHttpClient:
    """Stands in for httpx.AsyncClient, recording exactly what was sent."""

    def __init__(self, responses: list[_StubResponse]) -> None:
        self._responses = responses
        self.calls: list[dict] = []

    def __call__(self, *_args, **kwargs) -> "_StubHttpClient":
        self.timeout = kwargs.get("timeout")
        return self

    async def __aenter__(self) -> "_StubHttpClient":
        return self

    async def __aexit__(self, *_exc) -> bool:
        return False

    async def post(self, url: str, headers: dict, content: bytes) -> _StubResponse:
        self.calls.append({"url": url, "headers": headers, "content": content})
        return self._responses.pop(0)


def _with_stub_http(responses: list[_StubResponse], call):
    """Run `call(client)` against a stubbed transport, then put httpx back.

    Restoring matters: these modules share a process under a test runner, and a
    permanently monkeypatched `httpx.AsyncClient` would silently swallow every
    later HTTP call in the suite.
    """
    from app.prava import wallet as wallet_module

    stub = _StubHttpClient(responses)
    original = wallet_module.httpx.AsyncClient
    wallet_module.httpx.AsyncClient = stub  # type: ignore[assignment]
    try:
        return call(WalletClient("agent_test", VEC_PRIVATE)), stub
    finally:
        wallet_module.httpx.AsyncClient = original  # type: ignore[assignment]


def test_client_signs_the_exact_bytes_it_sends() -> None:
    """The signed message must be the body on the wire, not a re-serialization.

    This is the failure that produces a valid-looking request the server refuses:
    sign a dict, then let httpx serialize it again with different separators, and
    the two disagree by two characters per key.
    """
    _, stub = _with_stub_http(
        [_StubResponse(200, {"success": True, "data": {"ok": 1}})],
        lambda client: asyncio.run(
            client.post("/v1/wallet/shop/search", {"query": "coffee", "limit": 5})
        ),
    )

    sent = stub.calls[0]
    body_on_the_wire = sent["content"].decode()
    assert body_on_the_wire == '{"query":"coffee","limit":5}'
    assert verify_request(
        VEC_PUBLIC,
        sent["headers"]["X-Timestamp"],
        body_on_the_wire,
        sent["headers"]["X-Signature"],
    )
    assert sent["headers"]["X-Agent-Id"] == "agent_test"
    assert sent["headers"]["X-Skill-Name"] == "prava-shopping"
    # Unix SECONDS. A millisecond timestamp reads as ~55,000 years hence and the
    # server rejects it as expired.
    assert len(sent["headers"]["X-Timestamp"]) == 10


def test_client_raises_the_servers_own_error_code() -> None:
    try:
        _with_stub_http(
            [
                _StubResponse(
                    401,
                    {"error": {"code": "AUTH_INVALID_SIGNATURE", "message": "Missing or expired signature"}},
                )
            ],
            lambda client: asyncio.run(client.post("/v1/wallet/shop/search", {"query": "x"})),
        )
    except WalletError as exc:
        assert exc.code == "AUTH_INVALID_SIGNATURE"
        assert exc.status == 401
        assert "signature" in str(exc).lower()
    else:  # pragma: no cover
        raise AssertionError("expected WalletError")


def test_client_treats_a_200_with_success_false_as_a_failure() -> None:
    """The wallet reports declines inside a 200 envelope."""
    try:
        _with_stub_http(
            [
                _StubResponse(
                    200,
                    {"success": False, "error": {"code": "SHOP_SESSION_EXPIRED", "message": "expired"}},
                )
            ],
            lambda client: asyncio.run(client.post("/v1/wallet/shop/checkout", {})),
        )
    except WalletError as exc:
        assert exc.code == "SHOP_SESSION_EXPIRED"
    else:  # pragma: no cover
        raise AssertionError("expected WalletError")


def test_client_surfaces_the_replayed_flag() -> None:
    """A replay is a prior terminal result, NOT a fresh charge."""
    try:
        _with_stub_http(
            [
                _StubResponse(
                    200,
                    {"success": False, "replayed": True, "error": {"code": "X", "message": "already processed"}},
                )
            ],
            lambda client: asyncio.run(client.post("/v1/wallet/shop/checkout", {})),
        )
    except WalletError as exc:
        assert exc.replayed is True
    else:  # pragma: no cover
        raise AssertionError("expected WalletError")


# ── the shop broker ───────────────────────────────────────────────────────────

class _FakeWallet:
    """Scripted wallet: maps a path to a response or a raiser."""

    def __init__(self, routes: dict[str, object]) -> None:
        self.routes = routes
        self.calls: list[tuple[str, dict]] = []

    async def post(self, path: str, body: dict | None = None, *, timeout_s: float = 30.0) -> dict:
        self.calls.append((path, body or {}))
        handler = self.routes[path]
        if callable(handler):
            return handler(body or {}, len([c for c in self.calls if c[0] == path]))
        if isinstance(handler, Exception):
            raise handler
        return handler  # type: ignore[return-value]


def _context(budget_cents: int = 20000, rules: list[str] | None = None) -> PurchaseContext:
    return PurchaseContext(
        profile="business",
        approved_merchants=[Merchant(name="Bones Coffee", url="https://bonescoffee.com")],
        budget_cents=budget_cents,
        rules=rules if rules is not None else [],
    )


def _search_hit(product_id: str = "p1", title: str = "Costa Rica Single-Origin") -> dict:
    return {
        "results": [
            {"product_id": product_id, "merchant": "bonescoffee.com", "title": title,
             "price_estimate": {"amount": "19.99", "currency": "USD"}}
        ],
        "has_more": False,
    }


def _product(variants: list[dict]) -> dict:
    return {"product": {"id": "p1", "merchant": "bonescoffee.com", "variants": variants}}


def _variant(vid: str, price_cents: int, *, domain: str = "bonescoffee.com", available: bool = True, label: str = "12oz whole bean") -> dict:
    return {
        "id": vid,
        "label": label,
        "priceAmount": price_cents,
        "currency": "USD",
        "available": available,
        "options": [],
        "merchantDomain": domain,
    }


def _quote(total: str = "27.98", *, session: str = "checkout_1", subtotal: int = 1999, shipping: int = 799, tax: int = 0) -> dict:
    return {
        "checkout_session_id": session,
        "merchant": "bonescoffee.com",
        "final_price": {"amount": total, "currency": "USD"},
        "price_breakdown": {
            "subtotal_cents": subtotal,
            "shipping_cents": shipping,
            "tax_cents": tax,
            "currency": "USD",
        },
        "expires_at": "2026-08-02T18:30:00.000Z",
    }


def test_merchant_domain_and_query_shaping() -> None:
    assert merchant_domain("https://www.BonesCoffee.com/shop") == "bonescoffee.com"
    # The keyword query drops the imperative and the budget; the full sentence
    # still travels as `intent`.
    assert search_query("Order us some dark roast coffee under $200") == "dark roast coffee"


def test_build_cart_quotes_the_cheapest_allowed_variant() -> None:
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product([_variant("v-expensive", 4999), _variant("v-cheap", 1999)]),
            "/v1/wallet/shop/quote": _quote(),
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    cart = asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))

    quoted = [body for path, body in wallet.calls if path == "/v1/wallet/shop/quote"]
    assert quoted[0]["variant_id"] == "v-cheap"
    assert cart.total_cents == 2798
    assert cart.checkout.session_ref == "checkout_1"
    # The rows a human reads before approving MUST add up to what is charged.
    assert sum(i.qty * i.price_cents for i in cart.items) == cart.total_cents
    assert [i.name for i in cart.items] == ["Costa Rica Single-Origin", "Shipping"]


def test_build_cart_never_leaves_the_approved_merchant() -> None:
    """`product` lists every seller of an item; only the pinned one is buyable.

    The card `run_errand` mints is scoped to the policy merchant, so a variant
    from another seller is both a policy breach and a guaranteed decline.
    """
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product(
                [_variant("v-other", 999, domain="cheapcoffee.example"), _variant("v-ours", 1999)]
            ),
            "/v1/wallet/shop/quote": _quote(),
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))
    quoted = [body for path, body in wallet.calls if path == "/v1/wallet/shop/quote"]
    assert quoted[0]["variant_id"] == "v-ours"


def test_build_cart_applies_the_policy_prohibition() -> None:
    """The same rule reading as the storefront shopper — one policy, two paths."""
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(title="Energy drinks 6 x 250ml"),
            "/v1/wallet/shop/product": _product([_variant("v1", 1500, label="6-pack")]),
            "/v1/wallet/shop/quote": _quote(),
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    try:
        asyncio.run(
            broker.build_cart(
                "https://bonescoffee.com", "restock", _context(rules=["Do not purchase energy drinks"])
            )
        )
    except PravaShopError as exc:
        assert "fits the policy" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("a banned product must not be quoted")
    assert not [c for c in wallet.calls if c[0] == "/v1/wallet/shop/quote"]


def test_build_cart_refuses_to_shop_a_merchant_the_policy_did_not_name() -> None:
    wallet = _FakeWallet({"/v1/wallet/shop/search": {"results": [], "has_more": False}})
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    try:
        asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))
    except PravaShopError as exc:
        assert "policy did not name" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected a refusal rather than a wider search")


def test_build_cart_skips_variants_over_budget() -> None:
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product([_variant("v-big", 90000)]),
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    try:
        asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context(6000)))
    except PravaShopError as exc:
        assert "budget" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected an over-budget refusal")


def test_line_items_collapse_when_the_breakdown_does_not_reconcile() -> None:
    """Numbers on the approval screen must sum to the charge, or say one number."""
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product([_variant("v1", 1999)]),
            # A merchant discount the breakdown does not explain: 19.99 + 7.99
            # is 27.98, but the total charged is 24.98.
            "/v1/wallet/shop/quote": _quote("24.98"),
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    cart = asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))
    assert cart.total_cents == 2498
    assert len(cart.items) == 1
    assert sum(i.qty * i.price_cents for i in cart.items) == 2498


_CREDENTIAL = PaymentCredential(
    token="4323126882557932",
    dynamic_cvv="957",
    expiry_month="12",
    expiry_year="2027",
    txn_ref_id="tli_1",
)


def _parked(total_cents: int = 2798, session: str = "checkout_1") -> CheckoutState:
    return CheckoutState(
        merchant_url="https://bonescoffee.com",
        items=[CartItem(name="Coffee", qty=1, price_cents=total_cents)],
        session_ref=session,
    )


def test_checkout_pays_and_reports_the_order() -> None:
    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/checkout": {
                "status": "paid",
                "order_id": "ord_123",
                "amount": {"amount": "27.98", "currency": "USD"},
            }
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    order = asyncio.run(broker.complete_checkout(_parked(), _CREDENTIAL))
    assert order.order_id == "ord_123"
    assert "27.98" in order.confirmation_text
    # The credential maps onto the wallet's field names: dynamic_cvv → cryptogram.
    sent = wallet.calls[0][1]["credentials"]
    assert sent == {
        "token": "4323126882557932",
        "cryptogram": "957",
        "expiry_month": "12",
        "expiry_year": "2027",
    }


def test_checkout_that_is_not_paid_is_a_failure_not_an_order() -> None:
    wallet = _FakeWallet(
        {"/v1/wallet/shop/checkout": {"status": "declined", "failure_reason": "captcha required"}}
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    try:
        asyncio.run(broker.complete_checkout(_parked(), _CREDENTIAL))
    except PravaShopError as exc:
        assert "captcha" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("a declined checkout must not read as an order")


def test_expired_quote_is_repriced_and_paid_when_the_total_holds() -> None:
    """Approval + card entry can outlast a ~5 minute quote; that must recover."""
    state = {"checkout_calls": 0}

    def checkout(body: dict, _n: int) -> dict:
        state["checkout_calls"] += 1
        if body["checkout_session_id"] == "checkout_1":
            raise WalletError("Quote expired", code="SHOP_SESSION_EXPIRED")
        return {"status": "paid", "order_id": "ord_9", "amount": {"amount": "27.98", "currency": "USD"}}

    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product([_variant("v1", 1999)]),
            "/v1/wallet/shop/quote": lambda body, n: _quote(session=f"checkout_{n}"),
            "/v1/wallet/shop/checkout": checkout,
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    cart = asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))
    order = asyncio.run(broker.complete_checkout(cart.checkout, _CREDENTIAL))
    assert order.order_id == "ord_9"
    assert state["checkout_calls"] == 2


def test_a_price_that_moved_is_refused_rather_than_charged() -> None:
    """The card is scoped to the approved total. A different one is not ours to pay."""

    def checkout(body: dict, _n: int) -> dict:
        if body["checkout_session_id"] == "checkout_1":
            raise WalletError("Quote expired", code="SHOP_SESSION_EXPIRED")
        return {"status": "paid", "order_id": "ord_should_not_happen"}

    def quote(_body: dict, n: int) -> dict:
        # Second quote comes back dearer than the one the human approved.
        return _quote("31.98" if n > 1 else "27.98", session=f"checkout_{n}")

    wallet = _FakeWallet(
        {
            "/v1/wallet/shop/search": _search_hit(),
            "/v1/wallet/shop/product": _product([_variant("v1", 1999)]),
            "/v1/wallet/shop/quote": quote,
            "/v1/wallet/shop/checkout": checkout,
        }
    )
    broker = PravaShopBroker(wallet)  # type: ignore[arg-type]
    cart = asyncio.run(broker.build_cart("https://bonescoffee.com", "buy coffee", _context()))
    try:
        asyncio.run(broker.complete_checkout(cart.checkout, _CREDENTIAL))
    except PravaShopError as exc:
        assert exc.code == "PRICE_MOVED"
        assert "27.98" in str(exc) and "31.98" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("a moved price must never be charged silently")
    # Exactly one checkout attempt reached the wallet — the second was refused
    # locally, before any card was presented.
    assert len([c for c in wallet.calls if c[0] == "/v1/wallet/shop/checkout"]) == 1


def _run_all() -> None:
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"  ok  {name}")


if __name__ == "__main__":
    _run_all()
    print("\nall wallet tests passed")
